version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    container_name: payload_backpop_demo_mongodb
    volumes:
      - backpop_vol2:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  backpop_vol2: